#!/usr/bin/expect -f

set timeout 10

spawn screen /dev/ttyUSB0

send "\r"

send "enable"

send "\r"

send "conf t"

send "\r"

send "int f0/0"

send "\r"

send "ip address 10.150.10.240 255.255.255.0"

send "\r"

send "no shut"

send "\r"

send "int f0/1"

send "\r"

send "ip address 10.150.200.1 255.255.255.0"

send "\r"

send "no shut"

interact
interact
